[project]
name = "llms-from-scratch"
version = "0.1.0"
description = "This is a repository to track various LLM related code from scratch."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
